### ISSUE TITLE
Interpretability of RTF function

### ISSUE THREAD

**Issue by fabilo12** [clemenskreutz/CVID-19-modelling#8]
With the parameters from the result "20200402T005237_model1_Delays__Germany__ge20_cum_fitS0" one obtains the turquoise curve for the sustained part of the RTF. The parameter toffset_TF=30 does not concide with with the initial drop of the curve. Fix maxt_TF to smaller value?
![RTF_function_issue](https://user-images.githubusercontent.com/62991551/78367906-17683800-75c3-11ea-97aa-6f61edc2dabb.png)

**Comment by clemenskreutz** [comment]
The plot above shows the extreme case where maxt_TF >> timescale_sust (=0.039).
Such a fast timescale corresponds to an almost instantaneous decline (without the delay part). Usually, the timescale of the decrease is slower, e.g. timescale_sust= 1, ..., 10.
In addition, maxt_TF should be within strict limits (e.g. 2<maxt_TF<15) because of rounding errors.
